// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // Remove macOS and Windows
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0bmfYQgmtz8XBdogPXFLhKHM25dDM6g',
    appId: '1:228259860759:web:f0915aa3970f08e1722752',
    messagingSenderId: '228259860759',
    projectId: 'ecommercedentista-acf93',
    authDomain: 'ecommercedentista-acf93.firebaseapp.com',
    storageBucket: 'ecommercedentista-acf93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GnFE7Ei5fHdmdWgcCD6xdfgUNR_AKXo',
    appId: '1:228259860759:android:6e17c757737286ad722752',
    messagingSenderId: '228259860759',
    projectId: 'ecommercedentista-acf93',
    storageBucket: 'ecommercedentista-acf93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0G8hFSsJQeDDjhzjJ0v9TP3aeBmjf_H0',
    appId: '1:228259860759:ios:d3ef2c6955f05ce2722752',
    messagingSenderId: '228259860759',
    projectId: 'ecommercedentista-acf93',
    storageBucket: 'ecommercedentista-acf93.appspot.com',
    androidClientId: '228259860759-3vafvpea4neoulmv8u3d4i9rl17rnmuj.apps.googleusercontent.com',
    iosClientId: '228259860759-8pbp3r9feqng6vfijh8s75kko0ctj4vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryAppCliente',
  );

}